export default {
  data(){
    return{
      allData: [
        {},
        {
          level: 1,
          bornLeft: 100,
          bornBottom: 800,
          floors: [
            {
              id: 101,
              width: 150,
              height: 10,
              top: 700,
              left: 550,
              events: "",
            },
            {
              id: 102,
              width: 100,
              height: 10,
              top: 600,
              left: 400,
              events: "",
            },
            {
              id: 103,
              width: 80,
              height: 10,
              top: 500,
              left: 700,
              events: "",
            },
            {
              id: 104,
              width: 150,
              height: 10,
              top: 450,
              left: 100,
              events: "",
            },
            {
              id: 105,
              width: 70,
              height: 10,
              top: 350,
              left: 500,
              events: "",
            },
            {
              id: 106,
              width: 60,
              height: 10,
              top: 300,
              left: 850,
              events: "",
            },
            {
              id: 107,
              width: 50,
              height: 10,
              top: 180,
              left: 855,
              events: "",
            },
            {
              id: 108,
              width: 40,
              height: 10,
              top: 100,
              left: 650,
              events: "",
            },
            {
              id: 109,
              width: 30,
              height: 10,
              top: 200,
              left: 320,
              events: "",
            },
            {
              id: 110,
              width: 30,
              height: 10,
              top: 120,
              left: 130,
              color: "green",
              events: "level2",
            }
          ]
        },
        {
          level: 2,
          bornLeft: 20,
          bornBottom: 50,
          floors: [
            {
              id: 201,
              width: 50,
              height: 10,
              top: 50,
              left: 0,
              events: "",
            },
            {
              id: 202,
              width: 400,
              height: 10,
              top: 60,
              left: 0,
              events: "slide50",
            },
            {
              id: 203,
              width: 10,
              height: 350,
              top: 0,
              left: 450,
              events: "",
            },
            {
              id: 204,
              width: 10,
              height: 280,
              top: 70,
              left: 420,
              events: "",
            },
            {
              id: 205,
              width: 20,
              height: 10,
              top: 340,
              left: 430,
              color: "red",
              events: "die",
            },
            {
              id: 206,
              width: 50,
              height: 10,
              top: 130,
              left: 0,
              events: "",
            },
            {
              id: 207,
              width: 390,
              height: 10,
              top: 230,
              left: 30,
              color: "red",
              events: "die",
            },
            {
              id: 208,
              width: 10,
              height: 60,
              top: 70,
              left: 280,
              events: "",
            },
            {
              id: 209,
              width: 10,
              height: 120,
              top: 110,
              left: 70,
              events: "",
            },
            {
              id: 210,
              width: 10,
              height: 430,
              top: 240,
              left: 80,
              events: "",
            },
            {
              id: 211,
              width: 50,
              height: 10,
              top: 400,
              left: 0,
              color: "red",
              events: "die",
            },
            {
              id: 212,
              width: 50,
              height: 10,
              top: 550,
              left: 30,
              color: "red",
              events: "die",
            },
            {
              id: 213,
              width: 50,
              height: 10,
              top: 660,
              left: 90,
              events: "",
            },
            {
              id: 214,
              width: 90,
              height: 10,
              top: 550,
              left: 90,
              events: "",
            },
            {
              id: 215,
              width: 130,
              height: 10,
              top: 440,
              left: 90,
              events: "",
            },
            {
              id: 216,
              width: 50,
              height: 10,
              top: 320,
              left: 290,
              events: "",
            },
            {
              id: 217,
              width: 30,
              height: 10,
              top: 320,
              left: 460,
              events: "",
            },
            {
              id: 218,
              width: 30,
              height: 10,
              top: 210,
              left: 580,
              events: "remove217",
            },
            {
              id: 219,
              width: 10,
              height: 180,
              top: 40,
              left: 570,
              events: "",
            },
            {
              id: 220,
              width: 30,
              height: 10,
              top: 160,
              left: 460,
              events: "",
            },
            {
              id: 299,
              width: 1000,
              height: 10,
              top: 790,
              left: 0,
              color: "red",
              events: "die",
            },
          ]
        }
      ]
    }
  }
};
